services:
  viewer:
    image: evosurf/viewer:stable
    environment:
      - ACCESS_KEY=${ACCESS_KEY}
      - SESSION_ID=viewer-1
      - VIEWER_RUNTIME=docker
      - VIEWER_PLATFORM=linux
    restart: unless-stopped
    tmpfs:
      - /tmp
      - /dev/shm
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
